# Generated by Django 6.0.1 on 2026-01-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('training_goal', models.CharField(blank=True, choices=[('fat_loss', 'Fat loss / body composition'), ('strength', 'Strength & performance'), ('health', 'General health & fitness'), ('sport', 'Sport-specific training'), ('other', 'Other / not sure yet')], max_length=20)),
                ('coaching_option', models.CharField(blank=True, choices=[('1to1', '1:1 Personal Training'), ('small_group', 'Small Group Coaching'), ('large_group', 'Larger Group Classes'), ('online', 'Online Coaching')], max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time_window', models.CharField(blank=True, choices=[('early_morning', 'Early morning (06:00–09:00)'), ('late_morning', 'Late morning (09:00–12:00)'), ('early_afternoon', 'Early afternoon (12:00–15:00)'), ('late_afternoon', 'Late afternoon (15:00–18:00)'), ('evening', 'Evening (18:00–20:30)')], max_length=20)),
                ('availability_notes', models.TextField(blank=True)),
                ('training_background', models.TextField(blank=True)),
                ('contact_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
