# Generated by Django 6.0.1 on 2026-01-24 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_consultationrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMetricEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bodyweight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bench_top_set_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Heaviest top set for bench in kg.', max_digits=6, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text="Short label such as 'Upper Body — Week 3 / Day 2'.", max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=120)),
                ('set_number', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Working weight in kg (if applicable).', max_digits=6, null=True)),
                ('rpe', models.DecimalField(blank=True, decimal_places=2, help_text='RPE / effort rating for the set.', max_digits=4, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.workoutsession')),
            ],
            options={
                'ordering': ['session', 'exercise_name', 'set_number'],
            },
        ),
    ]
