# Generated by Django 6.0.1 on 2026-01-26 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_bodymetricentry_workoutsession_workoutset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='preferred_time_window',
            field=models.CharField(blank=True, choices=[('early_morning', 'Early morning (06:00-09:00)'), ('late_morning', 'Late morning (09:00-12:00)'), ('early_afternoon', 'Early afternoon (12:00-15:00)'), ('late_afternoon', 'Late afternoon (15:00-18:00)'), ('evening', 'Evening (18:00-20:30)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='name',
            field=models.CharField(help_text="Short label such as 'Upper Body - Week 3 / Day 2'.", max_length=120),
        ),
        migrations.CreateModel(
            name='ProgrammeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('weeks', models.PositiveIntegerField(default=4)),
                ('created_by', models.ForeignKey(blank=True, help_text='Trainer who created this programme template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_blocks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.programmeblock')),
            ],
            options={
                'ordering': ['block', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=120)),
                ('target_sets', models.PositiveIntegerField(default=3)),
                ('target_reps', models.PositiveIntegerField(default=10)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Planned working weight in kg (optional).', max_digits=5, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.programmeday')),
            ],
            options={
                'ordering': ['day', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ClientProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('completed', 'Completed')], default='active', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_programmes', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_programmes', to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training.programmeblock')),
            ],
            options={
                'verbose_name': 'Client programme',
                'verbose_name_plural': 'Client programmes',
                'unique_together': {('client', 'block')},
            },
        ),
    ]
