# Generated by Django 6.0.1 on 2026-01-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_programmeblock_template_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('logged', 'Logged'), ('planned', 'Planned'), ('skipped', 'Skipped')], default='logged', max_length=20),
        ),
    ]
