# Generated by Django 6.0.1 on 2026-01-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_workoutsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('contacted', 'Contacted'), ('closed', 'Closed'), ('added_classes', 'Added to classes')], default='new', max_length=20),
        ),
    ]
