# Generated by Django 6.0.1 on 2026-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_workoutsession_week_and_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('topic', models.CharField(choices=[('coaching', 'Coaching'), ('billing', 'Billing'), ('dashboard', 'Dashboard'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('urgency', models.CharField(choices=[('not_urgent', 'Not urgent'), ('few_days', 'Next few days'), ('asap', 'As soon as possible')], default='not_urgent', max_length=15)),
                ('contact_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
