# Generated by Django 6.0.1 on 2026-01-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_contactquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactquery',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='contactquery',
            name='topic',
        ),
        migrations.AddField(
            model_name='contactquery',
            name='coaching_option',
            field=models.CharField(choices=[('1to1', '1:1 Personal Training'), ('small_group', 'Small Group Coaching'), ('large_group', 'Larger Group Classes'), ('online', 'Online Coaching'), ('other', 'Other – please specify')], default='other', max_length=20),
        ),
    ]
