# Generated by Django 6.0.1 on 2026-01-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_remove_contactquery_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactquery',
            name='urgency',
        ),
    ]
