# Generated by Django 6.0.1 on 2026-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_remove_contactquery_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactquery',
            name='coaching_option',
            field=models.CharField(choices=[('1to1', '1:1 Personal Training'), ('small_group', 'Small Group Coaching'), ('large_group', 'Larger Group Classes'), ('online', 'Online Coaching'), ('other', 'Other – please specify')], max_length=20),
        ),
    ]
