# Generated by Django 6.0.1 on 2026-02-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_contactquery_assigned_trainer_drop_customerquery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactquery',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Contact queries'},
        ),
    ]
